package:
  name: pythonocc-core
  version: 0.16.2

source:
    git_url: https://github.com/tpaviot/pythonocc-core.git
    git_tag: review/smesh-6.5.3.1-support

build:
  number: 2
  binary_relocation: true

requirements:
  build:
    - cmake 3.0.1
    - python
    - opencascade_community_edition 0.16.1
    - smesh
    - boost
    - swig 3.0.2

  run:
    - python
    - opencascade_community_edition 0.16.1
    - boost
    - smesh

#test:
#  commands:
#    # You can put test commands to be run here.  Use this to test that the
#    # entry points work.
#    - nosetests test/run_tests.py
#
#
#  # You can also put a file called run_test.py in the recipe that will be run
#  # at test time.
#
#  requires:
#    # Put any additional test requirements here.  For example
#    - nose

about:
  home: https://github.com/tpaviot/pythonocc-core
  summary: https://github.com/tpaviot/pythonocc-core/blob/master/README.md
  license: LGPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
